title: aqrms
description: Just the Docs theme을 적용한 Jeykll site 입니다.
theme: just-the-docs
color_scheme: "dark"

url: https://aqrms.github.io/
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
